### ISSUE TITLE
request: nuke custodians?

### ISSUE THREAD

**Issue by androonuix** [Nuix/Nukers#1]
Hey Hey @JuicyDragon .  would you consider adding the capability to nuke custodians as part of this script?   i believe we have a legacy nuke custodians script floating around but it only works when the custodians are assigned.  ideally, such nuker functionality would remove assigned custodians and all references to custodians in a case.  thanks, -Andrew

**Comment by JuicyDragon** [comment]
Hello @androonuix I've added a "Custodian Nuker" script to this release:

https://github.com/Nuix/Nukers/releases/tag/v1.7.0

**Comment by androonuix** [comment]
@JuicyDragon  thank you!  you're a LEGEND.  <3 xoxo, androonuix and GlobalSupport Team
